haskell/haskeline

.gitignore
haskeline.cabal

By removing the dependency on Cabal >= 1.16 from `haskeline.cabal`, the installation of the library with versions of GHC without Cabal >= 1.16 is simplified.
Note: If this pull request is accepted, please release a new version. Thanks!

Removed unnecessary dependency on Cabal >= 1.16

---

System/Console/Haskeline/Directory.hsc

The #include of <Shlobj.h> doesn't work when cross-compiling from
Linux to Windows because the Linux file system is case sensitive and
on Linux the file is <shlobj.h>. This change should not affect Windows
builds because the Windows file system is case insensitive.

Fix Linux to Windows cross-compile

---

System/Console/Haskeline/Command.hs
System/Console/Haskeline/Monads.hs

This flips the AMP instance definitions into the recommended canonical form and makes the code a bit more future proof.

Canonicalise AMP instances

---

System/Console/Haskeline/InputT.hs

I'm not sure why the code was written the way it was, but it seems we
can do better by letting GHC directly reuse `ReaderT`'s instances as
well as relaxing the constraints from
instance Monad m       => Functor     (InputT m)
instance Monad m       => Applicative (InputT m)
instance Monad m       => Monad       (InputT m)
to
instance Functor     m => Functor     (InputT m)
instance Applicative m => Applicative (InputT m)
instance Monad       m => Monad       (InputT m)
This looks the same on GHC 7.8 (pre-AMP) as well as on GHC 7.10 (post-AMP)

Generalise constraints for InputT instances

---

haskeline.cabal

GHC 8.0 will ship with the not yet released `transformers-0.5.0.0`
release.

Relax upper bound to allow upcoming `transformers-0.5`

---

System/Console/Haskeline/Command/Completion.hs

This makes haskeline `-Wtabs`-clean

Untabify and delete trailing whitespace

---

.travis.yml
System/Console/Haskeline/Backend/Win32.hsc

In GHC 8.0, `hsc2hs` will introduce an `alignment` macro that is equivalent to the one manually defined in `System.Console.Haskeline.Backend.Win32`, which causes a [redefinition warning](https://mail.haskell.org/pipermail/ghc-devs/2015-December/010855.html):
```
Win32.hsc:170:0: error: "hsc_alignment" redefined [-Werror]
In file included from libraries/haskeline/dist-install/build/System/Console/Haskeline/Backend/Win32_hsc_make.c:1:0:
C:\code\HEAD\inplace/lib/template-hsc.h:88:0: note: this is the location of the previous definition
#define hsc_alignment(t...) \
^
```
This adds the simple fix of surrounding the `#let alignment ...` directive with `#if __GLASGOW_HASKELL__ < 711` to suppress the warning. (For some reason, `git diff` thinks I changed the entire file, but I think it's just my …

Suppress hsc2hs-related warning on GHC HEAD

---

System/Console/Haskeline/Emacs.hs

Haskeline differs from readline in C-w behaviour: 
* In readline unix-word-rubout (C-w) deleted one word to the left of the cursor, leaving the cursor in the position of the first letter of that word. (`123  45|6` -> `123  |6`)
* However, in ghci, it deletes the whitespaces before the word as well. (`123  45|6` -> `123|6`)

Fix the behavior of unix-word-rubout (C-w) for emacs bindings

---

System/Console/Haskeline.hs

Change outdated (I suppose so) `wrapInterrupt` to actual `withInterrupt`.

Fix withInterrupt function docs

---

System/Console/Haskeline/Backend/Posix.hsc

This function really has nothing to do with `Dynamic`.

Use cast from Data.Typeable instead of Data.Dynamic

---

Changelog
System/Console/Haskeline/Backend/Win32.hsc

Fixes #54 by adopting the strategy proposed in https://github.com/judah/haskeline/issues/54#issuecomment-280510726: refine the filtering criteria in `processEvent` so that it does not discard a keyup event if it comes from holding the left alt key and also emits a valid Unicode character, [mimicking the strategy present in `libuv`](https://github.com/libuv/libuv/blob/02dcde08386441d5a89dbcb602a1ad367a506cc0/src/win/tty.c#L730-L735).

Properly process Unicode key events on Windows

---

haskeline.cabal

This is necessary for GHC 8.2.

Bump upper bound on process

---

System/Console/Haskeline/Backend/Win32.hsc

MessageBeep expects an unsigned argument, leading to a
literal-out-of-range error previously.

Use 0xffffffff in place of -1 to MessageBeep

---

System/Console/Haskeline/MonadException.hs
haskeline.cabal

The `MonadException IdentityT` instance was missing.

Add MonadException IdentityT instance

---

System/Console/Haskeline/Backend/Posix.hsc
System/Console/Haskeline/Backend/Win32.hsc
System/Console/Haskeline/Term.hs
haskeline.cabal

The isEmptyChan broken has been long known to be broken. Moreover, the atomicity guarantees provided by STM simplify things a bit.

Move away from Chan to STM

---

haskeline.cabal

See https://ghc.haskell.org/trac/ghc/ticket/15042.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/82)

Bump upper bound on unix to < 2.9

---

haskeline.cabal

This is necessary for GHC 8.6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/83)

Bump stm upper bound

---

haskeline.cabal

This is needed for early integration w/ GHC HEAD for the 
upcoming GHC 8.8/base-4.13
Please do not upload this to Hackage before there isn't at least
a beta/RC of GHC 8.8 as only then the `base`-API would be
reasonably stable/frozen for base-4.13.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/104)

Declare tentative compatibility with unreleased GHC 8.8/base-4.13

---

haskeline.cabal
tests/RunTTY.hs
tests/Unit.hs

This works with `stack` and `cabal new-test`.  The latter
uses the `build-tool-depends` field to locate the binary.
Also:
- Remove the reference to the nonexistent main file on Windows.
- Make the test binary return a nonzero exit code when it fails.
Still TODO: test in CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/110)

Convert the test to a test-suite.

---

Changelog
System/Console/Haskeline/InputT.hs

There are also a couple of other monads that could plausibly have this
instance, but since none of them seem to be exported I left them alone.

Add a MonadFail instance for InputT.

---

System/Console/Haskeline/Backend/DumbTerm.hs
System/Console/Haskeline/Backend/Terminfo.hs

This will be necessary to compile with GHC 8.12. See GHC Proposal 287:
https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0287-simplify-subsumption.rst
I have submitted this against `haskeline-0.8` due to #133 but this will ultimately need to end up on `master` as well.

Eta expand as required by simplified subsumption rules

---

System/Console/Haskeline/Command/Completion.hs

Resolves #142
Modifies `makeLines` and `padWords` to use `gsWidth . stringToGraphemes` instead of `length` to count the visual width of strings instead of counting the number of characters.

Use grapheme's width to align a list of completions

---

System/Console/Haskeline/Backend/Win32.hsc

Win32 provides a few console primitives as of the 2.9 release, resulting
in name shadowing warnings with our own local versions. Hide those from
Win32 to avoid the warnings.

Win32: Hide console primitives from Win32-2.9

---

haskeline.cabal

Context: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4082#note_300462

Bump base upper bound to 4.16

---

System/Console/Haskeline/Backend/Posix.hsc
System/Console/Haskeline/Backend/WCWidth.hs
System/Console/Haskeline/Command/History.hs
haskeline.cabal

This will avoid future breakage
See https://downloads.haskell.org/ghc/8.10.3/docs/html/users_guide/using-warnings.html?highlight=wcompat#ghc-flag--Wcompat-unqualified-imports

Add import list to Data.List

---

System/Console/Haskeline/Backend/Posix.hsc

As noted by GHC #20085, the ccall calling convention does not support
variadic functions like `ioctl`.

Use capi rather than ccall to import ioctl

---

System/Console/Haskeline/Backend/Posix.hsc

If termios.h doesn't exist (e.g. in wasi-libc), we should be using a stub instead, otherwise hsc2hs panics at compile-time.

Check for termios.h existence

---

haskeline.cabal

Bump base bound to <4.20

---

System/Console/Haskeline/Backend/Win32.hsc
haskeline.cabal

We continue the adding support Windows Aarch64 (bump versions)
* bump `base` to latest
* bump `Win32` support to latest

Add support Windows Aarch64 (bump versions)

---

System/Console/Haskeline/Backend/Win32.hsc

The following https://gitlab.haskell.org/ghc/ghc/-/jobs/2098586
```
===> Command failed with error code: 1
libraries\haskeline\System\Console\Haskeline\Backend\Win32.hsc:19:17: error: [GHC-61689] [-Wdodgy-imports, Werror=dodgy-imports]
Module `System.Win32' does not export `InputEvent'.
|
19 |                 InputEvent,
|                 ^^^^^^^^^^
libraries\haskeline\System\Console\Haskeline\Backend\Win32.hsc:576:9: error: [GHC-63397] [-Wname-shadowing, Werror=name-shadowing]
This binding for `windowSize' shadows the existing binding
imported from `System.Win32' at libraries\haskeline\System\Console\Haskeline\Backend\Win32.hsc:(14,1)-(24,17)
(and originally defined in `Win32-2.14.1.0:System.Win32.Console.Internal')
|
576 |     let windowSize = width lay * height lay
|         ^^^^^^^^^^ …
```

Add support Windows Aarch64 (fix ghc warnings)

---

System/Console/Haskeline/InputT.hs

solving issue #150 
renamed readPrefsFromHome -> readUserPrefs
made readUserPrefs look for $XDG_CONFIG_HOME, check if it exists
and if so, readPrefs from it instead of $HOME/.haskeline.
If it doesen't exist, readPref from $HOME/.haskeline.

Added XDG support

---

haskeline.cabal

Fix #159: exclude Win32-2.10/11.
`haskeline >= 0.7.2.3` fails to build with `Win32-2.10/11` because of duplicate definitions:
```
Ambiguous occurrence `c_WaitForSingleObject'
It could refer to
either `System.Win32.c_WaitForSingleObject',
imported from `System.Win32' at System\Console\Haskeline\Backend\Win32.hsc:14:1-80
(and originally defined in `System.Win32.Event')
or `System.Console.Haskeline.Backend.Win32.c_WaitForSingleObject',
defined at dist\build\System\Console\Haskeline\Backend\Win32.hs:51:1
```

Fix #159: exclude Win32-2.10/11

---

System/Console/Haskeline.hs

The `\STX`-handling functionality is rather hard to discover: it's nowhere in the haddocks, only only on the GitHub wiki (which is not linked anywhere from Hackage, as the README is also not included on Hackage). (It is implemented in `stringToGraphemes` [here](https://github.com/haskell/haskeline/blob/105b62bc6bbacc67b13a38bfcd31423ea1e441db/System/Console/Haskeline/LineState.hs#L109).) Furthermore, this functionality is also not "standard": `bash` parses `\[` and `\]` specially to `readline` tokens (currently [here](https://git.savannah.gnu.org/cgit/bash.git/tree/y.tab.c#n8330)); they may happen to be `\001` and `\002`, but this is an implementation detail more than anything else.
This is a small patch to make this functionality more discoverable. (I wanted it in `ghci`.)
More broadly, …

Note wiki link about \ESC...\STX in haddocks

---

.github/workflows/haskell-ci.yml
haskeline.cabal

This is to allow containers-0.8 for GHC.
Note that haskeline-0.8.2.1 allows base-4.21 (due to a Hackage revision) but haskeline-0.8.3.0 doesn't. I'm just allowing it here for now, maybe you would like to make a revision for 0.8.3.0 too.
Also, I tried running the tests but some of them are already failing. There are no new failures with this PR.

Allow base-4.21 and containers-0.8

---

haskeline.cabal

Bump base upper bound to <4.23

---

System/Console/Haskeline.hs
System/Console/Haskeline/Command.hs
System/Console/Haskeline/Command/Completion.hs
System/Console/Haskeline/Command/KillRing.hs
System/Console/Haskeline/Emacs.hs
System/Console/Haskeline/Internal.hs
System/Console/Haskeline/Monads.hs
System/Console/Haskeline/Vi.hs

While investigating https://github.com/haskell/haskeline/issues/60 and trying to get my head around this code, I've realized that a `>|>` operator is defined that is no more than the fish operator `Control.Monad.(>=>)`, just with a different precedence.
I think this makes the code less readable for no benefit, because one has to shove one more symbol in their head, plus the memory to remember it has a given meaning, so with this change I'm substituting `>|>` with `>=>` throughout.
Clearly, to avoid having to put `(...)` here and there, I also changed the precedence of `+>` which is often used with that.
The code `cabal build`s, which I suppose is enough for this type of change?

Use (>=>) from Control.Monad instead of custom (>|>)

---

Changelog
System/Console/Haskeline/Backend/Win32.hsc
haskeline.cabal

This reverses commit f827f10145380ec9e685a72e4b8a7a27ef6717ea of 11 September 2010 (about 5 years before the November 2015 Update to Windows 10 made the native consoles on Windows 10 ANSI-capable). Applications like `GHCi` and `stack` enable the ANSI-capability of the native consoles. 
In respect of legacy Windows, none of them have mainstream support by Microsoft and Windows 7 loses extended support on 14 January 2020.
It has been tested on Windows 10 with
````haskell
module Main where
import System.Console.Haskeline
main :: IO ()
main = runInputT defaultSettings loop
where
prompt = "\ESC[34m\STXBlue\ESC[39m\STX\n\ESC[31m\STXRed\ESC[39m\STX: "
loop :: InputT IO ()
loop = do
minput <- getInputLine prompt
case minput of
Nothing -> pure ()
Just "quit" -> pure ()
Just input -> do outputStrLn …
```

Fix #130 Don't skip "\ESC...\STX" sequences (when terminal-style) 
