haskell/haskeline

haskeline.cabal

See haskell/filepath@d039d5ae7c070452a443219fdb7df65508567338

Allow new filepath-1.4 for GHC 7.10.1RC3

---

.travis.yml

Also drop all but the last release of 7.4, 7.6, 7.8 and 7.10.

.travis.yml: Add ghc 8.0.1

---

Changelog
README.md
System/Console/Haskeline.hs

Also bump to 0.7.4.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/73)

Clean up the rest of the references to trac.haskell.org.

---

haskeline.cabal

See https://ghc.haskell.org/trac/ghc/ticket/15018.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/81)

Bump upper bound on base to < 4.13

---

haskeline.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/86)

Bump upper bound on containers

---

appveyor.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/92)

Add an Appveyor build.

---

.travis.yml
System/Console/Haskeline/Backend/Terminfo.hs
System/Console/Haskeline/Backend/Win32.hsc
System/Console/Haskeline/InputT.hs
System/Console/Haskeline/MonadException.hs
System/Console/Haskeline/Monads.hs
System/Console/Haskeline/Term.hs
haskeline.cabal

Also:
- Add CI testing up to ghc-8.6.1
- Don't install explicit Cabal versions, now that we don't have
a custom Setup script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/94)

Bump the lower bound to ghc-8.0.

---

.travis.yml
System/Console/Haskeline/Backend/Posix.hsc
System/Console/Haskeline/Backend/Terminfo.hs
System/Console/Haskeline/Backend/Win32.hsc
System/Console/Haskeline/History.hs
System/Console/Haskeline/MonadException.hs
System/Console/Haskeline/Monads.hs
System/Console/Haskeline/RunCommand.hs
System/Console/Haskeline/Term.hs
stack.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/96)

Fix all warnings, and set `-Werror` in CI.

---

LICENSE

Fixes #21, which noted that the `LICENSE` file was inconsistent with
`License: BSD3` in the .cabal` file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/99)

Switch the `LICENSE` file to BSD3.

---

System/Console/Haskeline.hs

Fixes #3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/106)

Restructure the section about returning Nothing.

---

System/Console/Haskeline.hs
System/Console/Haskeline/RunCommand.hs

Fixes #72.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/107)

Fix `STX` appearing in any lines of the prompt, not just the last one.

---

Changelog
System/Console/Haskeline/Internal.hs
System/Console/Haskeline/Key.hs
haskeline.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/109)

Add `debugTerminalKeys`.

---

.travis.yml
stack.yaml

Also test ghc-8.6.3 in Travis CI instead of 8.6.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/judah/haskeline/113)

Bump the default lts to 13.3.

---

System/Console/Haskeline/Backend/DumbTerm.hs
System/Console/Haskeline/Backend/Terminfo.hs
haskeline.cabal

See GHC Proposal 287:
https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0287-simplify-subsumption.rst
Also bump `base` upper bound.

Eta expand as required by simplified subsumption rules

---

haskeline.cabal

Allow base-4.15

---

System/Console/Haskeline/Backend/Win32/Echo.hs

Hi,
We are looking to land a new I/O manager for Windows(`winio`) in GHC 8.12, See [1]
This package is a boot library and has used an internal GHC module (namely `GHC.IO.FD`)
as such it needs an update so that it works with `winio`.
The I/O manager is a runtime decision so users can switch at startup, this means that the
library needs to dynamically be able to switch between `winio` and `mio`. The combinator `(<!>)`
allows it to do so.
Change has been tested by bootstrapping GHC with new I/O manager enabled.
Thanks,
Tamar
[1] https://gitlab.haskell.org/ghc/ghc/-/merge_requests/1224

winio: Add support for WINIO to haskeline.

---

System/Console/Haskeline/Completion.hs

If we are completing symbols, word break chars are any non symbol characters, which are too long to enumerate.
See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6160

Add versions of completeWord{,withPrev} that take predicates for word break chars

---

haskeline.cabal

Bump base upper bound

---

haskeline.cabal

Cf. https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9370
CC @bgamari

Allow transformers-0.6

---

Changelog
System/Console/Haskeline/ReaderT.hs
haskeline.cabal

Resolves https://github.com/haskell/haskeline/issues/201.
I took the liberty of bumping the minor.
Thanks!

Add module for ReaderT interface
